---
sidebar: sidebar 
permalink: concept-overview.html 
keywords: overview, concepts, features, use case, cloud manager, bluexp, how bluexp works, supported cloud providers, cloud providers, hyperscalers 
summary: NetApp BlueXP为您的企业提供了一个控制平台、可帮助您在内部环境和云环境中构建、保护和管理数据。BlueXP SaaS平台包括可提供存储管理、数据移动性、数据保护以及数据分析和控制的服务。管理功能通过基于Web的控制台和API提供。 
---
= 了解BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp BlueXP为您的企业提供了一个控制平台、可帮助您在内部环境和云环境中构建、保护和管理数据。BlueXP SaaS平台包括可提供存储管理、数据移动性、数据保护以及数据分析和控制的服务。管理功能通过基于Web的控制台和API提供。



== 功能

BlueXP平台提供了数据管理的四大要素：存储、移动性、保护以及分析和控制。

存储:: 发现、部署和管理存储、无论是在AWS、Azure、Google Cloud中还是在内部环境中。
+
--
* 设置和使用 https://bluexp.netapp.com/ontap-cloud["Cloud Volumes ONTAP"^] 跨云实现高效的多协议数据管理。
* 设置和使用云文件存储服务：
+
** https://bluexp.netapp.com/azure-netapp-files["Azure NetApp Files"^]
** https://bluexp.netapp.com/fsx-for-ontap["适用于 ONTAP 的 Amazon FSX"^]
** https://bluexp.netapp.com/cloud-volumes-service-for-gcp["适用于 Google Cloud 的 Cloud Volumes Service"^]


* 发现和管理 https://bluexp.netapp.com/netapp-on-premises["内部存储"^]：
+
** E系列系统
** ONTAP 集群
** StorageGRID 系统




--
移动性:: 通过同步、复制、分层和缓存数据、将数据移动到需要的位置。
+
--
* https://bluexp.netapp.com/cloud-sync-service["复制和同步"^]
* https://bluexp.netapp.com/cloud-tiering["分层"^]


--
保护:: 使用自动化保护机制保护数据免受数据丢失、计划外中断、勒索软件和其他网络威胁的影响。
+
--
* https://bluexp.netapp.com/cloud-backup["备份和恢复"^]
* https://bluexp.netapp.com/replication["Replication"^]


--
分析和控制:: 使用工具监控、映射和优化数据存储和基础架构。获得可指导行动的智能信息、以优化存储运行状况、故障恢复能力和经济效益。
+
--
* https://bluexp.netapp.com/netapp-cloud-data-sense["分类"^]
* https://bluexp.netapp.com/digital-advisor["数字顾问"^]
* https://bluexp.netapp.com/digital-advisor["经济效率"^]
* https://bluexp.netapp.com/digital-advisor["运营故障恢复能力"^]


--


https://bluexp.netapp.com/["详细了解如何使用BlueXP帮助您的组织"^]



== 支持的云提供商

借助BlueXP、您可以在Amazon Web Services、Microsoft Azure和Google Cloud中管理云存储并使用云服务。



== 成本

BlueXP的定价取决于您计划使用的服务。 https://bluexp.netapp.com/pricing["了解有关BlueXP定价的信息"^]



== BlueXP的工作原理

BlueXP包括通过SaaS层提供的基于Web的控制台、提供多租户的帐户以及用于管理工作环境和启用BlueXP云服务的连接器。



=== 软件即服务

BlueXP可通过访问 https://console.bluexp.netapp.com["基于Web的控制台"^] 和 API 。通过这种SaaS体验、您可以在最新功能发布后自动访问这些功能、并轻松地在您的BlueXP帐户和连接器之间切换。



=== BlueXP帐户

首次登录到BlueXP时、系统会提示您创建一个_BlueXP帐户_。此帐户可提供多租户，并可用于在隔离的 _workworkworkspace _ 中组织用户和资源。

link:concept-netapp-accounts.html["了解有关客户的更多信息"]。



=== 连接器

您无需使用Connector即可开始使用BlueXP、但您需要创建一个Connector来解锁所有BlueXP功能和服务。通过Connector、您可以管理内部环境和云环境中的资源和流程。它是管理工作环境(例如Cloud Volumes ONTAP和内部ONTAP集群)以及使用许多BlueXP数据服务所必需的。

link:concept-connectors.html["了解有关连接器的更多信息"]。



=== 受限模式和专用模式

在具有安全和连接限制的环境中也支持BlueXP。您可以使用_restricted mode"或_private mode"来限制与BlueXP SaaS层的出站连接。

link:concept-modes.html["详细了解BlueXP部署模式"]。



== SOC 2 类型 2 认证

一家独立的注册会计师事务所和服务审计师对BlueXP进行了检查、并确认它根据适用的信任服务标准获得了SOC 2类型2报告。

https://www.netapp.com/company/trust-center/compliance/soc-2/["查看 NetApp 的 SOC 2 报告"^]
