---
sidebar: sidebar 
permalink: concept-data-services.html 
keywords: 'concept, connectors, learn about connectors, what are connectors, what is a connector, what"s a connector, days, 14 days, when is a connector required, connector supported locations, restricted mode, private mode, dark site, permissions, multiple connectors, disaster recovery' 
summary: Connector是在云网络或内部网络中运行的NetApp软件。它会执行BlueXP管理数据基础架构所需执行的操作。Connector会不断轮询BlueXP SaaS层以了解它需要执行的任何操作。您无需使用Connector即可开始使用BlueXP、但您需要创建一个Connector来解锁所有BlueXP功能和服务。 
---
= 了解BlueXP  服务
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp BlueXP为您的企业提供了一个控制平台、可帮助您在内部环境和云环境中构建、保护和管理数据。

您可以选择是使用BlueXP  SaaS服务(标准模式)、在受限云环境(受限模式)中运行BlueXP 、还是将其安装在您自己的内部数据中心内(私有模式)。无论您的环境如何、您都可以利用集中式管理和其他数据服务来保持存储资源的正常运行和安全。

您选择的模式决定了哪些服务可供您使用以及您可以管理哪些存储资源。

开始之前、请比较每种模式支持的不同存储资源以及可用的数据服务、以帮助您确定哪些存储资源符合公司的需求。



== 数据服务

下表显示了在每个部署模式下可用的数据服务、您是否需要订阅以及何时需要支持帐户。

[NOTE]
====
*连接器*表中的连接器列表示何时需要标准模式的连接器。如果您在受限模式或私用模式下使用BlueXP 、则始终需要具有连接器。

====
[cols="24,19,19,19,19"]
|===
|  | 需要支持帐户 | 需要连接器 | 需要订阅 | 模式可用性 


| 警报 | 是的。 | 是的。 | 否 | 全部 


| 备份和恢复 | 是的。 | 是的。 | 是的。 | 标准、受限 


| 分类 | 是的。 | 否 | 否 | 全部 


| 复制和同步 | 否 | 否 | 是的。 |  


| 数字顾问 | 是的。 | 否 | 否 | 全部 


| 数字电子钱包 | 是的。 | 否* | 否 | 全部 


| 灾难恢复 | 否 | 是的。 | 是的。 | 标准、受限 


| 经济效率 | 是的。 | 是的。 | 否 |  


| 运营故障恢复能力 | 是的。 | 是 * | 否 |  


| 勒索软件保护 | 否 | 是的。 | 否 | 标准 


| Replication | 否 | 否* | 否 | 标准、受限 


| 软件更新 | 是的。 | 否 | 否 | 全部 


| 支持案例管理 | 是的。 | 否 | 否 | 全部 


| 分层 | 否 | 否* | 是的。 | 标准 


| 卷缓存 | 否 | 否 | 否 | 标准 
|===


== NetApp存储

您可以直接从BlueXP  管理大多数NetApp存储资源、从而可以从同一应用程序查看所有资源。

下表列出了您可以从每种部署模式管理哪些存储资源、以及您是否需要Connector或订阅。

[NOTE]
====
*连接器*表中的连接器列表示何时需要标准模式的连接器。如果您在受限模式或私用模式下使用BlueXP 、则始终需要具有连接器。

====
[cols="24,19,19,19,19"]
|===
|  | 需要支持帐户 | 需要连接器 | 需要订阅 | 模式可用性 


| 适用于 NetApp ONTAP 的 Amazon FSX | 是的。 | 否^1^ | 是的。 | 标准 


| Amazon S3存储 | 是的。 | 否 | 是的。 | 标准 


| Azure Blb存储 | 是的。 | 否 | 否 | 标准 


| Azure NetApp Files | 否 | 否^2^ | 是的。 | 标准、受限 


| Cloud Volumes ONTAP | 是的。 | 是的。 | 是的。 | 标准、受限 


| 适用于 Google Cloud 的 Cloud Volumes Service | 否 | 否 | 是吗？ | 标准 


| E系列系统 | 否 | 是的。 | 否 | 标准 


| Google Cloud 存储 | 否 | 是的。 | 是吗？ | 标准 


| 内部 ONTAP 集群 | 是的。 | 否^3^ | 否 | 全部 


| StorageGRID | 是的。 | 是的。 | 否 | 标准、受限 
|===
^1^某些操作需要连接器或BlueXP  工作负载出厂链接。 https://docs.netapp.com/us-en/bluexp-fsx-ontap/start/concept-fsx-aws.html["了解哪些操作需要连接器或链路"^]

^2^虽然设置和管理Azure NetApp Files不需要连接器、但如果要使用BlueXP  分类扫描Azure NetApp Files数据、则需要连接器。

^3^虽然直接发现内部ONTAP集群不需要连接器、但如果要利用其他BlueXP  功能、则需要连接器。 https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html["了解有关内部ONTAP 集群的发现和管理选项的更多信息"^]
