---
sidebar: sidebar 
permalink: concept-connectors.html 
keywords: 'concept, connectors, learn about connectors, what are connectors, what is a connector, what"s a connector, days, 14 days, when is a connector required, connector supported locations, restricted mode, private mode, dark site, permissions, multiple connectors, disaster recovery' 
summary: Connector是在云网络或内部网络中运行的NetApp软件。它会执行BlueXP管理数据基础架构所需执行的操作。Connector会不断轮询BlueXP SaaS层以了解它需要执行的任何操作。您无需使用Connector即可开始使用BlueXP、但您需要创建一个Connector来解锁所有BlueXP功能和服务。 
---
= 了解BlueXP  连接器
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
_Connector_是在云网络或内部网络中运行的NetApp软件。它用于将 BlueXP 的服务连接到您的存储环境。



== 没有连接器可以执行的操作

开始使用BlueXP无需使用Connector。您可以在BlueXP中使用多种功能和服务、而无需创建Connector。

您可以在不使用Connector的情况下使用以下BlueXP功能和服务：

* 适用于 NetApp ONTAP 的 Amazon FSX
+
某些操作需要使用连接器或BlueXP  工作负载出厂链接。 https://docs.netapp.com/us-en/bluexp-fsx-ontap/start/concept-fsx-aws.html["了解哪些操作需要连接器或链路"^]

* 自动化目录
* Azure NetApp Files
+
虽然设置和管理Azure NetApp Files 不需要使用连接器、但如果要使用BlueXP分类扫描Azure NetApp Files 数据、则需要使用连接器。

* 适用于 Google Cloud 的 Cloud Volumes Service
* 复制和同步
* 数字顾问
* 电子钱包(仅限许可证、订阅监控需要连接器)
+
在几乎所有情况下、您都可以在没有连接器的情况下向数字钱包添加许可证。

+
仅当需要使用Connector向数字钱包添加许可证时、才需要使用Cloud Volumes ONTAP _no-based _许可证。在这种情况下，需要使用连接器，因为数据是从 Cloud Volumes ONTAP 系统上安装的许可证中获取的。

* 直接发现内部ONTAP 集群
+
虽然直接发现内部ONTAP 集群不需要连接器、但如果要利用其他BlueXP功能、则需要连接器。

+
https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html["了解有关本地 ONTAP 集群的发现和管理选项的更多信息"^]

* 软件更新
* 可持续性
* 工作负载工厂




== 需要连接器时

在标准模式下使用BlueXP时、需要使用Connector才能在BlueXP中实现以下功能和服务：

* 警报
* 适用于 ONTAP 的 Amazon FSX 管理功能
* Amazon S3存储
* Azure Blb存储
* 备份和恢复
* 分类
* Cloud Volumes ONTAP
* 灾难恢复
* E系列系统
* 经济效益^1^
* Google Cloud存储分段
* 与BlueXP数据服务的内部ONTAP 集群集成
* 运营弹性^1^
* 勒索软件保护
* StorageGRID 系统
* 分层
* 卷缓存


^1^虽然您可以在没有连接器的情况下访问这些服务、但要从这些服务启动操作、需要使用连接器。

要在受限模式或专用模式下使用BlueXP、需要使用Connector。



== 连接器必须始终正常运行

连接器是BlueXP服务架构的基本组成部分。您有责任确保相关连接器始终正常运行且可访问。虽然此服务旨在克服连接器可用性短暂中断的问题、但您必须在需要时立即采取措施来修复基础架构故障。

本文档受EULA约束。如果未按照文档操作产品，则产品的功能和操作以及您在 EULA 下的权利可能会受到不利影响。



== 支持的位置

以下位置支持连接器：

* Amazon Web Services
* Microsoft Azure
+
Azure中的连接器应部署在与它所管理的Cloud Volumes ONTAP系统相同的Azure区域中、或者对于Cloud Volumes ONTAP系统、应部署在中 https://docs.microsoft.com/en-us/azure/availability-zones/cross-region-replication-azure#azure-cross-region-replication-pairings-for-all-geographies["Azure 区域对"^]。此要求可确保在Cloud Volumes ONTAP及其关联存储帐户之间使用Azure专用链接连接。 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-enabling-private-link.html["了解 Cloud Volumes ONTAP 如何使用 Azure 专用链路"^]

* Google Cloud
+
如果要将BlueXP服务与Google Cloud结合使用、则必须使用在Google Cloud中运行的Connector。

* 在您的内部环境中




== 与云提供商进行通信

Connector使用TLS 1.3与AWS、Azure和Google Cloud进行所有通信。



== 受限模式和专用模式

要在受限模式或专用模式下使用BlueXP、您可以先安装Connector、然后访问在Connector上本地运行的用户界面、从而开始使用BlueXP。

link:concept-modes.html["了解BlueXP部署模式"]。



== 如何安装连接器

您可以直接从 BlueXP、云提供商的市场安装连接器，也可以在您自己的 Linux 主机上手动安装该软件。如何开始取决于您是在标准模式、受限模式还是专用模式下使用BlueXP。

* link:concept-modes.html["了解BlueXP部署模式"]
* link:task-quick-start-standard-mode.html["以标准模式开始使用BlueXP"]
* link:task-quick-start-restricted-mode.html["开始在受限模式下使用BlueXP"]
* link:task-quick-start-private-mode.html["开始在私有模式下使用BlueXP"]




== 权限

直接从BlueXP创建Connector需要特定权限、而Connector实例本身也需要另一组权限。如果您直接从BlueXP在AWS或Azure中创建Connector、则BlueXP将使用所需权限创建Connector。

在标准模式下使用BlueXP时、如何提供权限取决于您计划如何创建Connector。

要了解如何设置权限、请参见以下内容：

* 标准模式
+
** link:concept-install-options-aws.html["AWS中的连接器安装选项"]
** link:concept-install-options-azure.html["Azure中的连接器安装选项"]
** link:concept-install-options-google.html["Google Cloud中的连接器安装选项"]
** link:task-install-connector-on-prem.html#step-4-set-up-cloud-permissions["为本地部署设置云权限"]


* link:task-prepare-restricted-mode.html#step-6-prepare-cloud-permissions["设置受限模式的权限"]
* link:task-prepare-private-mode.html#step-6-prepare-cloud-permissions["设置私有模式的权限"]


要查看Connector日常操作所需的确切权限、请参阅以下页面：

* link:reference-permissions-aws.html["了解Connector如何使用AWS权限"]
* link:reference-permissions-azure.html["了解Connector如何使用Azure权限"]
* link:reference-permissions-gcp.html["了解Connector如何使用Google Cloud权限"]


在后续版本中添加新权限时、您有责任更新Connector策略。如果需要新的权限、这些权限将在发行说明中列出。



== 连接器升级

我们通常每月更新一次 Connector 软件，以引入新功能并提高稳定性。虽然BlueXP  平台中的大多数服务和功能都是通过基于SaaS的软件提供的、但少数功能取决于Connector的版本。其中包括 Cloud Volumes ONTAP 管理、on-premisesONTAP 集群管理、设置和帮助。

当您在标准模式或受限模式下使用BlueXP时、Connector会自动将其软件更新到最新版本、只要它可以通过出站Internet访问来获取软件更新即可。如果您正在私有模式下使用BlueXP、则需要手动升级Connector。

link:task-upgrade-connector.html["了解如何在使用私有模式时手动升级Connector软件"](英文)



== 操作系统和VM维护

在Connector主机上维护操作系统是您(客户)的责任。例如、您(客户)应按照公司的操作系统分发标准过程对Connector主机上的操作系统应用安全更新。

请注意、在应用次要安全更新时、您(客户)不需要停止Connector主机上的任何服务。

如果您(客户)需要先停止再启动Connector VM、则应从云提供商的控制台执行此操作、或者使用内部管理的标准过程执行此操作。

<<连接器必须始终正常运行,请注意、连接器必须始终正常运行>>。



== 多种工作环境和连接器

一个Connector可以在BlueXP中管理多个工作环境。一个 Connector 应管理的最大工作环境数因情况而异。具体取决于工作环境的类型，卷数量，要管理的容量以及用户数量。

如果您要进行大规模部署，请与 NetApp 代表合作来估算您的环境规模。如果您在此过程中遇到任何问题，请通过产品内聊天联系我们。

在某些情况下，您可能只需要一个连接器，但可能需要两个或更多连接器。

以下是几个示例：

* 您有一个多云环境（例如，AWS 和 Azure），并且您希望在 AWS 中使用一个连接器，在 Azure 中使用另一个连接器。每个都管理在这些环境中运行的 Cloud Volumes ONTAP 系统。
* 服务提供商可以使用一个BlueXP  组织为其客户提供服务、而使用另一个组织为其业务部门之一提供灾难恢复。每个组织都有单独的连接器。

