---
sidebar: sidebar 
permalink: concept-connectors.html 
keywords: 'concept, connectors, learn about connectors, what are connectors, what is a connector, what"s a connector, days, 14 days, when is a connector required, connector supported locations, restricted mode, private mode, dark site, permissions, multiple connectors, disaster recovery' 
summary: Connector是在云网络或内部网络中运行的NetApp软件。它会执行BlueXP管理数据基础架构所需执行的操作。Connector会不断轮询BlueXP SaaS层以了解它需要执行的任何操作。您无需使用Connector即可开始使用BlueXP、但您需要创建一个Connector来解锁所有BlueXP功能和服务。 
---
= 了解连接器
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
_Connector_是在云网络或内部网络中运行的NetApp软件。它会执行BlueXP管理数据基础架构所需执行的操作。Connector会不断轮询BlueXP SaaS层以了解它需要执行的任何操作。您无需使用Connector即可开始使用BlueXP、但您需要创建一个Connector来解锁所有BlueXP功能和服务。



== 没有连接器可以执行的操作

开始使用BlueXP无需使用Connector。您可以在BlueXP中使用多种功能和服务、而无需创建Connector。

您可以在不使用Connector的情况下使用以下BlueXP功能和服务：

* 创建适用于NetApp ONTAP 的Amazon FSX工作环境
+
虽然创建工作环境不需要使用Connector、但需要使用它来创建和管理卷、复制数据以及将FSx for ONTAP 与BlueXP分类和BlueXP复制和同步等服务集成。

* 自动化目录
* Azure NetApp Files
+
虽然设置和管理Azure NetApp Files 不需要使用连接器、但如果要使用BlueXP分类扫描Azure NetApp Files 数据、则需要使用连接器。

* 适用于 Google Cloud 的 Cloud Volumes Service
* 复制和同步
* 数字顾问
* 数字电子钱包
+
在几乎所有情况下、您都可以在没有连接器的情况下向数字钱包添加许可证。

+
仅当需要使用Connector向数字钱包添加许可证时、才需要使用Cloud Volumes ONTAP _no-based _许可证。在这种情况下，需要使用连接器，因为数据是从 Cloud Volumes ONTAP 系统上安装的许可证中获取的。

* 直接发现内部ONTAP 集群
+
虽然直接发现内部ONTAP 集群不需要连接器、但如果要利用其他BlueXP功能、则需要连接器。

+
https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html["了解有关内部ONTAP 集群的发现和管理选项的更多信息"^]

* 可持续性




== 需要连接器时

在标准模式下使用BlueXP时、需要使用Connector才能在BlueXP中实现以下功能和服务：

* 适用于 ONTAP 的 Amazon FSX 管理功能
* Amazon S3存储
* Azure Blb存储
* 备份和恢复
* 分类
* Cloud Volumes ONTAP
* 灾难恢复
* E系列系统
* 经济效益^1^
* 边缘缓存
* Google Cloud存储分段
* Kubernetes 集群
* 迁移报告
* 与BlueXP数据服务的内部ONTAP 集群集成
* 运营弹性^1^
* StorageGRID 系统
* 分层
* 卷缓存


^1^虽然您可以在没有连接器的情况下访问这些服务、但要从这些服务启动操作、需要使用连接器。

要在受限模式或专用模式下使用BlueXP、需要使用Connector。



== 连接器必须始终正常运行

连接器是BlueXP服务架构的基本组成部分。您有责任确保相关连接器始终正常运行且可访问。虽然此服务旨在克服连接器可用性短暂中断的问题、但您必须在需要时立即采取措施来修复基础架构故障。

本文档受EULA约束。如果本产品未按照文档进行操作、则可能会对本产品的功能和运行以及您在EULA下的权利产生不利影响。



=== 对Cloud Volumes ONTAP 的影响

连接器是Cloud Volumes ONTAP 运行状况和运行的关键组件。如果某个连接器已关闭、则Cloud Volumes ONTAP PAYGO系统和基于容量的BYOL系统将在与某个连接器的通信中断14天后关闭。发生这种情况的原因是、Connector每天都会刷新系统上的许可。

如果您的Cloud Volumes ONTAP 系统具有基于节点的BYOL许可证、则该系统会在14天后保持运行、因为该许可证已安装在Cloud Volumes ONTAP 系统上。



== 支持的位置

以下位置支持连接器：

* Amazon Web Services
* Microsoft Azure
+
Azure中的连接器应部署在与其管理的Cloud Volumes ONTAP 系统所在的同一Azure区域或中 https://docs.microsoft.com/en-us/azure/availability-zones/cross-region-replication-azure#azure-cross-region-replication-pairings-for-all-geographies["Azure 区域对"^] 对于 Cloud Volumes ONTAP 系统。此要求可确保在 Cloud Volumes ONTAP 与其关联存储帐户之间使用 Azure 专用链路连接。 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-enabling-private-link.html["了解 Cloud Volumes ONTAP 如何使用 Azure 专用链路"^]

* Google Cloud
+
如果要将BlueXP服务与Google Cloud结合使用、则必须使用在Google Cloud中运行的Connector。

* 在您的内部环境中




== 受限模式和专用模式

要在受限模式或专用模式下使用BlueXP、您可以先安装Connector、然后访问在Connector上本地运行的用户界面、从而开始使用BlueXP。

link:concept-modes.html["了解BlueXP部署模式"]。



== 如何创建 Connector

BlueXP客户管理员可以直接从BlueXP、云提供商的市场或在您自己的Linux主机上手动安装软件来创建Connector。如何开始取决于您是在标准模式、受限模式还是专用模式下使用BlueXP。

* link:concept-modes.html["了解BlueXP部署模式"]
* link:task-quick-start-standard-mode.html["以标准模式开始使用BlueXP"]
* link:task-quick-start-restricted-mode.html["开始在受限模式下使用BlueXP"]
* link:task-quick-start-private-mode.html["开始在私有模式下使用BlueXP"]




== 权限

直接从BlueXP创建Connector需要特定权限、而Connector实例本身也需要另一组权限。如果您直接从BlueXP在AWS或Azure中创建Connector、则BlueXP将使用所需权限创建Connector。

在标准模式下使用BlueXP时、如何提供权限取决于您计划如何创建Connector。

要了解如何设置权限、请参见以下内容：

* 标准模式
+
** link:concept-install-options-aws.html["AWS中的连接器安装选项"]
** link:concept-install-options-azure.html["Azure中的连接器安装选项"]
** link:concept-install-options-google.html["Google Cloud中的连接器安装选项"]
** link:task-install-connector-on-prem.html#step-3-set-up-cloud-permissions["为内部部署设置云权限"]


* link:task-prepare-restricted-mode.html#step-5-prepare-cloud-permissions["设置受限模式的权限"]
* link:task-prepare-private-mode.html#step-5-prepare-cloud-permissions["设置私有模式的权限"]


要查看Connector日常操作所需的确切权限、请参阅以下页面：

* link:reference-permissions-aws.html["了解Connector如何使用AWS权限"]
* link:reference-permissions-azure.html["了解Connector如何使用Azure权限"]
* link:reference-permissions-gcp.html["了解Connector如何使用Google Cloud权限"]




== 连接器升级

我们通常每月更新一次 Connector 软件，以引入新功能并提高稳定性。虽然BlueXP平台中的大多数服务和功能均通过基于SaaS的软件提供、但有几项特性和功能取决于Connector的版本。其中包括 Cloud Volumes ONTAP 管理，内部 ONTAP 集群管理，设置和帮助。

当您在标准模式或受限模式下使用BlueXP时、Connector会自动将其软件更新到最新版本、只要它可以通过出站Internet访问来获取软件更新即可。如果您正在私有模式下使用BlueXP、则需要手动升级Connector。

link:task-managing-connectors.html["了解如何手动升级Connector软件"]。



== 操作系统和VM维护

您应负责维护Connector主机上的操作系统。例如、您应按照公司的操作系统分发标准过程对Connector主机上的操作系统应用安全更新。

请注意、在运行操作系统更新时、您无需停止Connector主机上的任何服务。

如果您需要先停止并启动Connector VM、则应从云提供商的控制台或使用内部管理的标准过程来执行此操作。

<<连接器必须始终正常运行,请注意、连接器必须始终正常运行>>。



== 多个工作环境

一个Connector可以在BlueXP中管理多个工作环境。一个 Connector 应管理的最大工作环境数因情况而异。具体取决于工作环境的类型，卷数量，要管理的容量以及用户数量。

如果您要进行大规模部署，请与 NetApp 代表合作来估算您的环境规模。如果您在此过程中遇到任何问题，请通过产品内聊天联系我们。



== 多个连接器

在某些情况下，您可能只需要一个连接器，但可能需要两个或更多连接器。

以下是几个示例：

* 您有一个多云环境(例如AWS和Azure)、并且更喜欢在AWS中使用一个Connector、而在Azure中使用另一个Connector。每个都管理在这些环境中运行的 Cloud Volumes ONTAP 系统。
* 服务提供商可能会使用一个BlueXP帐户为其客户提供服务、而使用另一个帐户为其某个业务部门提供灾难恢复。每个帐户都有单独的 Connectors 。




=== 何时切换

创建第一个Connector时、BlueXP会自动对您创建的每个附加工作环境使用该Connector。创建额外的 Connector 后，您需要在它们之间切换，以查看每个 Connector 特有的工作环境。

link:task-managing-connectors.html["了解如何在连接器之间切换"]。



=== 灾难恢复

您可以同时管理具有多个连接器的工作环境，以实现灾难恢复。如果一个连接器发生故障，您可以切换到另一个连接器以立即管理工作环境。

要设置此配置，请执行以下操作：

. link:task-managing-connectors.html["切换到另一个连接器"]。
. 发现现有工作环境。
+
** https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-adding-systems.html["将现有Cloud Volumes ONTAP 系统添加到BlueXP"^]
** https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html["发现 ONTAP 集群"^]


. 设置 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-storage-management.html["容量管理模式"^]
+
只能将主连接器设置为 * 自动模式 * 。如果出于灾难恢复目的而切换到另一个连接器，则可以根据需要更改容量管理模式。


