---
sidebar: sidebar 
permalink: reference-iam-predefined-roles.html 
keywords: predefined roles, iam roles, organization admin, folder or project admin, classification viewer, snapcenter admin, role, iam role, admin, iam, identity and access management 
summary: BlueXP  身份和访问管理包括多个预定义角色、您可以将这些角色分配给组织的成员。 
---
= 预定义的BlueXP  IAM角色和权限
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP  身份和访问管理(IAM)包括多个预定义角色、您可以将这些角色分配给组织中不同级别的资源层次结构成员。在分配这些角色之前、您应了解每个角色包含的权限。



== 平台角色

BlueXP  IAM包括两个平台角色：组织管理员和文件夹管理员或项目管理员。两个BlueXP  IAM平台角色之间的主要区别是范围。组织管理员角色在所有文件夹和项目中都有权限；而文件夹或项目管理员只在其所分配到的文件夹或项目中有权限。

文件夹或项目管理员角色无法创建连接器。

权限::


[cols="24,19,19"]
|===
| 任务 | 组织管理员 | 文件夹或项目管理员 


| 生成接头 | 是的。 | 否 


| 创建、修改或删除工作环境(使用BlueXP  画布添加或发现新资源) | 是的。 | 是的。 


| 创建项目/文件夹、包括重命名、删除和编辑 | 是的。 | 是的。 


| 分配角色和添加用户 | 是的。 | 是的。 


| 将资源和连接器与文件夹和项目相关联 | 是的。 | 是的。 


| 通过设置>凭据管理凭据 | 是的。 | 是的。 


| 查看BlueXP  时间线 | 是的。 | 是的。 


| 使用BlueXP  服务 | 是的。 | 是的。 


| 注册BlueXP  以获得支持并提交案例 | 是的。 | 是的。 
|===
大型跨国组织在BlueXP  中的组织角色示例:: XYZ Corporation是一家跨国公司、其目标是根据地理区域(北美、欧洲和亚太地区)隔离对数据存储资源的访问。他们希望每个区域在保持集中监督的同时，对其资源实行专属控制。
+
--
为此、在XYZ公司的BlueXP  中分配了组织管理员角色的人员会创建一个初始工作环境、然后在BlueXP  中为每个区域创建单独的文件夹。每个区域的文件夹都包含与该区域相关的项目(以及相关资源)。组织管理员为每个区域的BlueXP  用户分配文件夹/项目管理员角色。

完成初始设置后、具有文件夹或项目管理员角色的区域管理员可以创建新的工作环境并在其区域内添加用户。这些区域管理员还可以添加/删除/重命名为其分配的文件夹和项目。组织管理员可以继承任何新工作环境或资源的权限、从而保持整个组织内存储使用情况的可见性。

--




== 数据服务角色

数据服务角色可以在任何项目或文件夹中完成其任务。



=== SnapCenter管理员

Description:: 能够使用适用于应用程序的BlueXP  备份和恢复功能从内部ONTAP集群备份快照。
权限:: 具有此角色的成员可以在BlueXP  中完成以下操作：
+
--
* 从备份和恢复>应用程序完成任何操作
* 管理他们拥有权限的项目和文件夹中的所有工作环境
* 使用所有BlueXP  服务


--




=== 分类查看器

Description:: 提供查看BlueXP  分类扫描结果的功能。
权限:: 查看合规性信息并为其有权访问的资源生成报告。这些用户无法启用或禁用对卷、分段或数据库架构的扫描。
+
--
具有此角色的成员不能执行任何其他操作。

--




== 相关链接

* link:concept-identity-and-access-management.html["了解BlueXP  身份和访问管理"]
* link:task-iam-get-started.html["开始使用BlueXP  IAM"]
* link:task-iam-manage-members-permissions.html["管理BlueXP  成员及其权限"]
* https://docs.netapp.com/us-en/bluexp-automation/tenancyv4/overview.html["了解适用于BlueXP  IAM的API"^]

