---
sidebar: sidebar 
permalink: reference-connector-default-config.html 
keywords: linux, user name, operating system, installation files, installation folder, folder, log, logs, service, mysql, packages, linux, connector configuration, connector installation folder, connector folder, connector log, ubuntu 
summary: 您可能希望在部署连接器之前或需要对任何问题进行故障排除时了解有关连接器的更多信息。 
---
= Connector 的默认配置
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可能希望在部署连接器之前了解有关其配置的更多信息、或者需要对任何问题进行故障排除。



== 具有 Internet 访问权限的默认配置

如果您从BlueXP、云提供商的市场部署了Connector、或者在可访问Internet的内部Linux主机上手动安装了Connector、则以下配置详细信息适用。



=== AWS详细信息

如果您从BlueXP或云提供商的市场部署了Connector、请注意以下事项：

* EC2实例类型为t3.2 x大。
* 该映像的操作系统为Ubuntu 22.04 LTS。
+
操作系统不包含 GUI 。您必须使用终端访问系统。

* 此安装包括Docker引擎、这是所需的容器流程编排工具。
* EC2 Linux实例的用户名为Ubuntu (对于2023年5月之前创建的连接器、用户名为EC2-user)。
* 默认系统磁盘为100 GiB GP2磁盘。




=== Azure详细信息

如果您从BlueXP或云提供商的市场部署了Connector、请注意以下事项：

* VM类型为Standard"(标准)_D8s_v3。
* 该映像的操作系统为Ubuntu 22.04 LTS。
+
操作系统不包含 GUI 。您必须使用终端访问系统。

* 此安装包括Docker引擎、这是所需的容器流程编排工具。
* 默认系统磁盘为100 GiB高级SSD磁盘。




=== Google Cloud详细信息

如果您是从BlueXP部署连接器的、请注意以下事项：

* VM实例为n2-standard-8。
* 该映像的操作系统为Ubuntu 22.04 LTS。
+
操作系统不包含 GUI 。您必须使用终端访问系统。

* 此安装包括Docker引擎、这是所需的容器流程编排工具。
* 默认系统磁盘为100 GiB SSD永久性磁盘。




=== 安装文件夹

Connector 安装文件夹位于以下位置：

/opt/application/netapp/cloudmanager



=== 日志文件

日志文件包含在以下文件夹中：

* /opt/application/netapp/cloudmanager/log
或
* /opt/application/netapp/service-manager-2/logs (从新的3.9.23安装开始)
+
这些文件夹中的日志提供了有关Connector的详细信息。

* /opt/application/netapp/cloudmanager/docker_occm/data/log
+
此文件夹中的日志提供了有关云服务以及在Connector上运行的BlueXP服务的详细信息。





=== 连接器服务

* BlueXP服务名为occa。
* OCUM 服务依赖于 MySQL 服务。
+
如果 MySQL 服务已关闭，则 OCCM 服务也将关闭。





=== 端口

Connector 在 Linux 主机上使用以下端口：

* 80 用于 HTTP 访问
* 443用于HTTPS访问




== 无 Internet 访问的默认配置

如果您在无法访问 Internet 的内部 Linux 主机上手动安装了 Connector ，则以下配置适用。 link:task-quick-start-private-mode.html["了解有关此安装选项的更多信息"]。

* Connector 安装文件夹位于以下位置：
+
/opt/application/netapp/ds.

* 日志文件包含在以下文件夹中：
+
/var/lib/docker/volumes/ds_occmdata/_data/log

+
此文件夹中的日志提供了有关连接器和 Docker 映像的详细信息。

* 所有服务均在 Docker 容器中运行
+
这些服务取决于运行的 Docker 运行时服务

* Connector 在 Linux 主机上使用以下端口：
+
** 80 用于 HTTP 访问
** 443用于HTTPS访问



