---
sidebar: sidebar 
permalink: reference-networking-saas-console.html 
keywords: networking, urls, endpoints, web browser, console, network, set up networking 
summary: 当您使用通过SaaS层提供的基于Web的BlueXP控制台时、它会在完成一些管理任务时与多个端点联系。访问BlueXP控制台的计算机应连接到这些端点。 
---
= 为BlueXP  控制台准备网络连接
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
当您使用通过SaaS层提供的基于Web的BlueXP控制台时、它会在完成一些管理任务时与多个端点联系。访问BlueXP控制台的计算机应连接到这些端点。

在BlueXP控制台中完成特定操作时、系统会从用户的计算机访问这些端点。您还应参考Connector和特定BlueXP服务的网络连接要求。有关详细信息、请参见本页末尾的相关链接。

[cols="2*"]
|===
| 端点 | 目的 


| \https://console.bluexp.netapp.com
\https://*.console.bluexp.netapp.com | 使用BlueXP基于Web的控制台时、Web浏览器会联系这些URL。 


| \https://aiq.netapp.com | 需要访问BlueXP数字顾问。 


 a| 
AWS 服务（ AmazonAWS.com ）：

* 云形成
* 弹性计算云（ EC2 ）
* 密钥管理服务（ KMS ）
* 安全令牌服务（ STS ）
* 简单存储服务 (S3)

| 在AWS中从BlueXP部署连接器时需要此功能。确切的端点取决于部署 Connector 的区域。 https://docs.aws.amazon.com/general/latest/gr/rande.html["有关详细信息，请参阅 AWS 文档。"^] 


| \https://management.azure.com

\https://login.microsoftonline.com | 在大多数Azure地区从BlueXP部署连接器时需要此功能。 


| \https://management.microsoftazure.de

\https://login.microsoftonline.de | 在Azure德国地区从BlueXP部署连接器时需要此功能。 


| \https://management.usgovcloudapi.net

\https://login.microsoftonline.com | 在Azure US Gov地区从BlueXP部署连接器时需要此功能。 


| \https://www.googleapis.com | 在Google Cloud中从BlueXP部署Connector时需要此功能。 


| \https://signin.b2c.netapp.com | 需要更新NetApp 支持站点 (NSS)凭据或向BlueXP添加新的NSS凭据。 


| \https://netapp-cloud-account.auth0.com

\https://cdn.auth0.com

\https://services.cloud.netapp.com | 您的Web浏览器连接到这些端点、以便通过BlueXP集中进行用户身份验证。 


| \https://widget.intercom.io | 用于与 NetApp 云专家交流的产品内聊天。 
|===
除了这些端点之外、您还需要确保Connector可以通过出站Internet访问来联系特定端点以进行日常操作。您可以通过以下下一节中的链接找到这些端点的列表。

.相关信息
* 为连接器准备网络连接
+
** link:task-install-connector-aws-bluexp.html#step-1-set-up-networking["设置AWS网络"]
** link:task-install-connector-azure-bluexp.html#step-1-set-up-networking["设置Azure网络"]
** link:task-install-connector-google-bluexp-gcloud.html#step-1-set-up-networking["设置Google Cloud网络"]
** link:task-install-connector-on-prem.html#step-3-set-up-networking["设置内部网络"]


* 为BlueXP服务准备网络连接
+
请参阅每个BlueXP服务的文档。

+
https://docs.netapp.com/us-en/bluexp-family/["BlueXP文档"^]


