---
sidebar: sidebar 
permalink: reference-networking-saas-console.html 
keywords: networking, urls, endpoints, web browser, console, network, set up networking 
summary: 开始使用BlueXP时、请确保您的网络允许从BlueXP控制台访问特定端点。根据您计划如何使用BlueXP、您可能还需要为Connector和特定BlueXP服务设置网络连接。 
---
= 准备网络连接
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
开始使用BlueXP时、请确保您的网络允许从BlueXP控制台访问特定端点。根据您计划如何使用BlueXP、您可能还需要为Connector和特定BlueXP服务设置网络连接。



== 为用户访问BlueXP控制台准备网络连接

当您使用通过SaaS层提供的基于Web的BlueXP控制台时、它会与多个端点联系以完成数据管理任务。运行Web浏览器的计算机必须连接到这些端点。

[cols="2*"]
|===
| 端点 | 目的 


| \https://console.bluexp.netapp.com
\https://*.console.bluexp.netapp.com | 使用BlueXP基于Web的控制台时、Web浏览器会联系这些URL。 


 a| 
AWS 服务（ AmazonAWS.com ）：

* 云形成
* 弹性计算云（ EC2 ）
* 密钥管理服务（ KMS ）
* 安全令牌服务（ STS ）
* 简单存储服务 (S3)

| 在AWS中从BlueXP部署连接器时需要此功能。确切的端点取决于部署 Connector 的区域。 https://docs.aws.amazon.com/general/latest/gr/rande.html["有关详细信息，请参阅 AWS 文档。"^] 


| \https://management.azure.com

\https://login.microsoftonline.com | 在大多数Azure地区从BlueXP部署连接器时需要此功能。 


| \https://management.microsoftazure.de

\https://login.microsoftonline.de | 在Azure德国地区从BlueXP部署连接器时需要此功能。 


| \https://management.usgovcloudapi.net

\https://login.microsoftonline.com | 在Azure US Gov地区从BlueXP部署连接器时需要此功能。 


| \https://www.googleapis.com | 在Google Cloud中从BlueXP部署Connector时需要此功能。 


| \https://signin.b2c.netapp.com | 需要更新NetApp 支持站点 (NSS)凭据或向BlueXP添加新的NSS凭据。 


| \https://netapp-cloud-account.auth0.com

\https://cdn.auth0.com

\https://services.cloud.netapp.com | 您的Web浏览器连接到这些端点、以便通过BlueXP集中进行用户身份验证。 


| \https://widget.intercom.io | 用于与 NetApp 云专家交流的产品内聊天。 
|===
除了这些端点之外、您还需要确保Connector可以通过出站Internet访问来联系特定端点以进行日常操作。您可以通过以下下一节中的链接找到这些端点的列表。



== 为连接器准备网络连接

如何为Connector准备网络取决于您计划将Connector安装在何处、可以安装在云中、也可以安装在内部环境中。有关连接器网络连接要求的详细信息、请参阅以下页面：

* link:task-set-up-networking-aws.html["设置AWS网络"]
* link:task-set-up-networking-azure.html["设置Azure网络"]
* link:task-set-up-networking-google.html["设置Google Cloud网络"]
* link:task-set-up-networking-on-prem.html["设置内部网络"]




== 为BlueXP服务准备网络连接

开始使用BlueXP时、您应确保满足计划使用的BlueXP服务的网络连接要求。有关详细信息、请参见每项服务的文档。

https://docs.netapp.com/us-en/bluexp-family/["BlueXP文档"^]
