---
sidebar: sidebar 
permalink: reference-iam-platform-roles.html 
keywords: predefined roles, iam roles, organization admin, folder or project admin, classification viewer, snapcenter admin, role, iam role, admin, iam, identity and access management 
summary: 为用户分配平台角色，以授予管理BlueXP、分配角色、添加用户、创建连接器和管理联合的权限。 
---
= BlueXP  平台访问角色
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
为用户分配平台角色，以授予管理BlueXP、分配角色、添加用户、创建连接器和管理联合的权限。

.大型跨国组织在BlueXP  中的组织角色示例
XYZ 公司按地区（北美、欧洲和亚太地区）组织数据存储访问，从而提供区域控制和集中监督。

XYZ 公司的BlueXP中的 *组织管理员* 为每个区域创建一个初始组织和单独的文件夹。每个区域的*文件夹或项目管理员*在该区域的文件夹中组织项目（及相关资源）。

具有“文件夹或项目管理员”角色的区域管理员通过添加资源和用户来主动管理他们的文件夹。这些区域管理员还可以添加、删除或重命名他们管理的文件夹和项目。  *组织管理员*继承任何新资源的权限，保持整个组织的存储使用情况的可见性。

在同一个组织内，一名用户被分配了*联合管理员*角色来管理该组织与其企业 IdP 的联合。该用户可以添加或删除联合组织，但不能管理组织内的用户或资源。  *组织管理员*为用户分配*联合查看者*角色，以检查联合状态并查看联合组织。

下表列出了每个BlueXP平台角色可以执行的操作。



== 组织管理角色

[cols="2,1,1"]
|===
| 任务 | 组织管理员 | 文件夹或项目管理员 


| 创建连接器 | 是的。 | 否 


| 创建、修改或删除工作环境(使用BlueXP  画布添加或发现新资源) | 是的。 | 是的。 


| 创建文件夹和项目、包括删除 | 是的。 | 否 


| 重命名现有文件夹和项目 | 是的。 | 是的。 


| 分配角色和添加用户 | 是的。 | 是的。 


| 将资源与文件夹和项目相关联 | 是的。 | 是的。 


| 将接头与文件夹和项目相关联 | 是的。 | 否 


| 从文件夹和项目中删除接头 | 是的。 | 否 


| 管理连接器(编辑证书、设置等) | 是的。 | 否 


| 通过设置>凭据管理凭据 | 是的。 | 是的。 


| 创建、管理和查看联合 | 是的。 | 否 


| 通过BlueXP注册支持并提交案例 | 是的。 | 是的。 


| 使用数据服务 | 是的。 | 是的。 


| 查看BlueXP时间线和通知 | 是的。 | 是的。 
|===


== 联盟角色

[cols="2,1,1"]
|===
| 任务 | 联盟管理员 | 联合查看器 


| 创建联盟 | 是的。 | 否 


| 验证域名 | 是的。 | 否 


| 将域添加到联合 | 是的。 | 否 


| 禁用和删除联盟 | 是的。 | 否 


| 测试联盟 | 是的。 | 否 


| 查看联盟及其详细信息 | 是的。 | 是的。 
|===