---
sidebar: sidebar 
permalink: reference-iam-platform-roles.html 
keywords: predefined roles, iam roles, organization admin, folder or project admin, classification viewer, snapcenter admin, role, iam role, admin, iam, identity and access management 
summary: BlueXP  身份和访问管理包括多个预定义角色、您可以将这些角色分配给组织的成员。 
---
= BlueXP  平台访问角色
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
平台角色是您可以分配给用户的最广泛角色、并且允许使用所有权限进行BlueXP管理、包括分配角色和添加用户。具有平台角色的用户可以访问BlueXP  中的所有数据服务和应用程序。BlueXP  包括两个平台角色：*组织管理员*和*文件夹或项目管理员*。这两个BlueXP  平台角色之间的主要区别在于该角色所适用的范围。

.大型跨国组织在BlueXP  中的组织角色示例
XYZ Corporation是一家跨国公司、其目标是根据地理区域(北美、欧洲和亚太地区)隔离对数据存储资源的访问。他们希望每个区域在保持集中监督的同时，对其资源实行专属控制。

为此，在XYZ公司的BlueXP  中分配了*组织管理员*角色的人员会创建一个初始工作环境，然后在BlueXP  中为每个区域创建单独的文件夹。每个区域的文件夹都包含与该区域相关的项目(以及相关资源)。组织管理员*为每个区域的BlueXP  用户分配*文件夹或项目管理员*角色。

初始设置完成后，具有*文件夹或项目管理员*角色的区域管理员可以创建新的工作环境并在其区域内添加用户。这些区域管理员还可以添加/删除/重命名为其分配的文件夹和项目。组织管理员*可以继承对任何新工作环境或资源的权限，从而保持整个组织内存储使用情况的可见性。

下表显示了每个BlueXP  平台角色可以执行的操作。

[cols="2,1,1"]
|===
| 任务 | 组织管理员 | 文件夹或项目管理员 


| 创建连接器 | 是的。 | 否 


| 创建、修改或删除工作环境(使用BlueXP  画布添加或发现新资源) | 是的。 | 是的。 


| 创建文件夹和项目、包括删除 | 是的。 | 否 


| 重命名现有文件夹和项目 | 是的。 | 是的。 


| 分配角色和添加用户 | 是的。 | 是的。 


| 将资源与文件夹和项目相关联 | 是的。 | 是的。 


| 将接头与文件夹和项目相关联 | 是的。 | 否 


| 从文件夹和项目中删除接头 | 是的。 | 否 


| 管理连接器(编辑证书、设置等) | 是的。 | 否 


| 通过设置>凭据管理凭据 | 是的。 | 是的。 


| 查看BlueXP  时间线 | 是的。 | 是的。 


| 使用BlueXP  服务 | 是的。 | 是的。 


| 注册BlueXP  以获得支持并提交案例 | 是的。 | 是的。 
|===