---
sidebar: sidebar 
permalink: task-installing-linux.html 
keywords: install connector, manually install connector, install connector software, installation, installing, linux, installer, software, on prem, on-prem, silent, configurations, ec2, vm, ports, ram, operating system, os, host, requirement, requirements, hypervisor, disk, space, mysql, centos, rhel, red hat, cpu, disk space 
summary: 创建Connector的最常见方法是直接从BlueXP或云提供商的市场创建。但是，您可以选择在网络或云中的现有 Linux 主机上下载并安装 Connector 软件。这些步骤特定于可访问 Internet 的主机。 
---
= 在可访问 Internet 的现有 Linux 主机上安装 Connector
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
创建Connector的最常见方法是直接从BlueXP或云提供商的市场创建。但是，您可以选择在网络或云中的现有 Linux 主机上下载并安装 Connector 软件。这些步骤特定于可访问 Internet 的主机。

link:concept-connectors.html["了解部署 Connector 的其他方法"]。


NOTE: 如果要在 Google Cloud 中创建 Cloud Volumes ONTAP 系统，则必须同时在 Google Cloud 中运行 Connector 。您不能使用在 AWS ， Azure 或内部运行的 Connector 。



== 验证主机要求

连接器软件必须在满足特定操作系统要求， RAM 要求，端口要求等要求的主机上运行。

需要一个专用主机:: 与其他应用程序共享的主机不支持此连接器。主机必须是专用主机。
CPU:: 4 个核心或 4 个 vCPU
RAM:: 14 GB
AWS EC2 实例类型:: 满足上述 CPU 和 RAM 要求的实例类型。我们建议使用 T3.xlarge 。
Azure 虚拟机大小:: 满足上述 CPU 和 RAM 要求的实例类型。我们建议使用 DS3 v2 。
GCP 计算机类型:: 满足上述 CPU 和 RAM 要求的实例类型。我们建议使用n2-standard-4。
+
--
在具有支持的操作系统的VM实例上、Google Cloud支持Connector https://cloud.google.com/compute/shielded-vm/docs/shielded-vm["屏蔽VM功能"^]

--
支持的操作系统::
+
--
* CentOS 7.6、7.7、7.8和7.9
* Red Hat Enterprise Linux 7.6、7.7、7.8、7.9、8.6、 和8.7
+
Red Hat Enterprise Linux 系统必须在 Red Hat 订购管理中注册。如果未注册，则在安装 Connector 期间，系统无法访问存储库来更新所需的第三方软件。

+
这些操作系统的英语版本支持 Connector 。



--
虚拟机管理程序:: 经过认证可运行 CentOS 或 Red Hat Enterprise Linux 的裸机或托管虚拟机管理程序https://access.redhat.com/certified-hypervisors["Red Hat 解决方案：哪些虚拟机管理程序已通过认证，可以运行 Red Hat Enterprise Linux ？"^]
/opt 中的磁盘空间:: 必须有 100 GiB 的可用空间
/var 中的磁盘空间:: 必须有 20 GiB 的可用空间
Docker 引擎:: 在安装Connector之前、主机上需要安装Docker引擎19.3.1或更高版本。 https://docs.docker.com/engine/install/["查看安装说明"^]
出站 Internet 访问:: 在安装过程中、Connector的安装程序必须访问以下URL：
+
--
* https://support.netapp.com
* https://mysupport.netapp.com
* https://cloudmanager.cloud.netapp.com/tenancy
* https://stream.cloudmanager.cloud.netapp.com
* https://cloudmanagerinfraprod.azurecr.io
* https://production-artifacts.cloudmanager.cloud.netapp.com
* https://*.blob.core.windows.net


主机可能会在安装期间尝试更新操作系统软件包。主机可以联系这些操作系统软件包的不同镜像站点。

--




== 安装连接器

确认您拥有受支持的 Linux 主机后，您可以获取 Connector 软件并进行安装。

.您需要的内容
* 安装Connector的root权限。
* 有关代理服务器的详细信息、如果从Connector访问Internet需要代理。支持HTTP和HTTPS。
+
您可以选择在安装后配置代理服务器、但这样做需要重新启动Connector。

* 如果代理服务器使用HTTPS、则为CA签名证书。


.关于此任务
* 此安装将安装 AWS 命令行工具（ awscli ），以便从 NetApp 支持部门执行恢复过程。
+
如果您收到安装 AWSCLI 失败的消息，则可以安全地忽略该消息。如果没有工具，连接器可以成功运行。

* NetApp 支持站点上提供的安装程序可能是早期版本。安装后，如果有新版本可用， Connector 会自动进行更新。


.步骤
. 验证 Docker 是否已启用且正在运行。
+
[source, cli]
----
sudo systemctl enable docker && sudo systemctl start docker
----
. 如果在主机上设置了_http_proxy_或_https_proxy_系统变量、请将其删除：
+
[source, cli]
----
unset http_proxy
unset https_proxy
----
+
如果不删除这些系统变量、安装将失败。

. 从下载Connector软件 https://mysupport.netapp.com/site/products/all/details/cloud-manager/downloads-tab["NetApp 支持站点"^]，然后将其复制到 Linux 主机。
+
您应下载适用于您的网络或云中的Connector安装程序。

. 分配运行脚本的权限。
+
[source, cli]
----
chmod +x OnCommandCloudManager-V3.9.23
----
. 运行安装脚本。
+
[source, cli]
----
 ./OnCommandCloudManager-V3.9.23 --proxy <HTTP or HTTPS proxy server> --cacert <path and file name of a CA-signed certificate>
----
+
-proxy和-cacert参数是可选的。如果您有代理服务器、则需要输入所示的参数。安装程序不会提示您提供有关代理的信息。

+
以下是使用这两个可选参数的命令示例：

+
[source, cli]
----
 ./OnCommandCloudManager-V3.9.23 --proxy https://user:password@10.0.0.30:8080/ --cacert /tmp/cacert/certificate.cer
----
+
-proxy会将Connector配置为使用以下格式之一的HTTP或HTTPS代理服务器：

+
** http://address:port
** http://username:password@address:port
** https://address:port
** https://username:password@address:port


+
-cacert指定用于在Connector和代理服务器之间进行HTTPS访问的CA签名证书。只有在指定HTTPS代理服务器时、才需要此参数。



.结果
此时将安装Connector。在安装结束时、如果您指定了代理服务器、则Connector服务(occa)将重新启动两次。



== 设置连接器

注册或登录、然后设置Connector以使用您的帐户。

.步骤
. 打开 Web 浏览器并输入以下 URL ：
+
https://_ipaddress_[]

+
_ipaddress_ 可以是 localhost ，专用 IP 地址或公有 IP 地址，具体取决于主机的配置。例如，如果连接器位于公有云中且没有公有 IP 地址，则必须输入与连接器主机连接的主机的专用 IP 地址。

. 注册或登录。
. 如果您在Google Cloud中安装了Connector、请设置一个服务帐户、该帐户具有BlueXP在项目中创建和管理Cloud Volumes ONTAP 系统所需的权限。
+
.. https://cloud.google.com/iam/docs/creating-custom-roles#iam-custom-roles-create-gcloud["在 GCP 中创建角色"^] 其中包括中定义的权限 link:reference-permissions-gcp.html["GCP的连接器策略"]。
.. https://cloud.google.com/iam/docs/creating-managing-service-accounts#creating_a_service_account["创建 GCP 服务帐户并应用刚刚创建的自定义角色"^]。
.. https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances#changeserviceaccountandscopes["将此服务帐户与 Connector VM 关联"^]。
.. 如果要在其他项目中部署 Cloud Volumes ONTAP ， https://cloud.google.com/iam/docs/granting-changing-revoking-access#granting-console["通过向该项目添加具有BlueXP角色的服务帐户来授予访问权限"^]。您需要对每个项目重复此步骤。


. 登录后、设置BlueXP：
+
.. 指定要与 Connector 关联的 NetApp 帐户。
+
link:concept-netapp-accounts.html["了解 NetApp 客户"]。

.. 输入系统名称。




.结果
现在，您可以使用 NetApp 帐户安装并设置 Connector 。在创建新的工作环境时、BlueXP将自动使用此Connector。

.完成后
设置权限、以便BlueXP可以管理公有 云环境中的资源和流程：

* AWS link:task-adding-aws-accounts.html["设置AWS帐户、然后将其添加到BlueXP"]
* Azure 酒店 link:task-adding-azure-accounts.html["设置Azure帐户、然后将其添加到BlueXP"]
* Google Cloud：请参见上面的第3步

