---
sidebar: sidebar 
permalink: task-install-connector-on-prem.html 
keywords: install connector, on prem connector installation, on prem connector, install connector on prem, manual install 
summary: 在内部安装Connector、然后登录并设置它以使用您的BlueXP帐户。 
---
= 在内部安装和设置连接器
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在内部安装Connector、然后登录并设置它以使用您的BlueXP帐户。



== 安装连接器

在内部现有Linux主机上下载并安装Connector软件。

.您需要的内容
* 安装Connector的root权限。
* 有关代理服务器的详细信息、如果从Connector访问Internet需要代理。
+
您可以选择在安装后配置代理服务器、但这样做需要重新启动Connector。

* CA签名证书、如果代理服务器使用HTTPS或代理是截获代理。


.关于此任务
NetApp 支持站点上提供的安装程序可能是早期版本。安装后，如果有新版本可用， Connector 会自动进行更新。

.步骤
. 验证 Docker 是否已启用且正在运行。
+
[source, cli]
----
sudo systemctl enable docker && sudo systemctl start docker
----
. 如果在主机上设置了_http_proxy_或_https_proxy_系统变量、请将其删除：
+
[source, cli]
----
unset http_proxy
unset https_proxy
----
+
如果不删除这些系统变量、安装将失败。

. 从下载Connector软件 https://mysupport.netapp.com/site/products/all/details/cloud-manager/downloads-tab["NetApp 支持站点"^]，然后将其复制到 Linux 主机。
+
您应下载用于您的网络或云中的"联机"Connector安装程序。Connector可以使用单独的"脱机"安装程序、但只有专用模式部署才支持此安装程序。

. 分配运行脚本的权限。
+
[source, cli]
----
chmod +x OnCommandCloudManager-<version>
----
+
其中、<version> 是您下载的连接器版本。

. 运行安装脚本。
+
[source, cli]
----
 ./OnCommandCloudManager-<version> --proxy <HTTP or HTTPS proxy server> --cacert <path and file name of a CA-signed certificate>
----
+
-proxy和-cacert参数是可选的。如果您有代理服务器、则需要输入所示的参数。安装程序不会提示您提供有关代理的信息。

+
以下是使用这两个可选参数的命令示例：

+
[source, cli]
----
 ./OnCommandCloudManager-V3.9.26 --proxy https://user:password@10.0.0.30:8080/ --cacert /tmp/cacert/certificate.cer
----
+
-proxy会将Connector配置为使用以下格式之一的HTTP或HTTPS代理服务器：

+
** \http://address:port
** \http://username:password@address:port
** \https://address:port
** \https://username:password@address:port
+
用户必须是本地用户。不支持域用户。



+
-cacert指定用于在Connector和代理服务器之间进行HTTPS访问的CA签名证书。只有在指定HTTPS代理服务器或代理为截获代理时、才需要此参数。



.结果
此时将安装Connector。在安装结束时、如果您指定了代理服务器、则Connector服务(occa)将重新启动两次。



== 设置连接器

注册或登录、然后设置Connector以使用您的帐户。

.步骤
. 打开 Web 浏览器并输入以下 URL ：
+
https://_ipaddress_[]

+
_ipaddress_ 可以是 localhost ，专用 IP 地址或公有 IP 地址，具体取决于主机的配置。例如，如果连接器位于公有云中且没有公有 IP 地址，则必须输入与连接器主机连接的主机的专用 IP 地址。

. 注册或登录。
. 登录后、设置BlueXP：
+
.. 指定要与Connector关联的BlueXP帐户。
.. 输入系统名称。
.. 在*是否在安全环境中运行？*下、保持禁用受限模式。
+
您应始终禁用受限模式、因为这些步骤说明了如何在标准模式下使用BlueXP。(此外、在内部安装Connector时、不支持受限模式。)

.. 单击*我们开始*。




.结果
现在、BlueXP已设置为使用您刚刚安装的Connector。

.下一步是什么？
link:task-provide-permissions-on-prem.html["为BlueXP提供您先前设置的权限"]。
