---
sidebar: sidebar 
permalink: task-set-up-permissions-aws.html 
keywords: aws permissions, set up permissions, set up aws permissions, permissions, iam role, iam policy, json, policy, role, credentials 
summary: 在AWS中设置权限、以便您可以使用管理数据和存储基础架构所需的权限部署Connector。如何设置和提供权限取决于您计划使用的安装选项。 
---
= 设置AWS权限
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在AWS中设置权限、以便您可以使用管理数据和存储基础架构所需的权限部署Connector。如何设置和提供权限取决于您计划使用的安装选项。

您可以从以下安装选项中进行选择：

* *从BlueXp安装*：设置权限、使BlueXP能够通过AWS进行身份验证并部署实例。在部署期间、BlueXP会自动为Connector实例设置权限。
+
<<设置从BlueXP创建Connector的权限,查看分步说明>>。

* *从AWS Marketplace安装*：设置可与Connector实例关联的IAM角色。
+
<<在从AWS Marketplace部署时设置Connector的权限,查看分步说明>>。

* *手动安装*：创建IAM策略并将其附加到IAM角色或IAM用户。
+
<<设置手动安装后要分配的权限,查看分步说明>>。





== 设置从BlueXP创建Connector的权限

BlueXP需要先向AWS进行身份验证、然后才能在VPC中部署Connector实例。您可以选择以下身份验证方法之一：

* 让BlueXP承担具有所需权限的IAM角色
* 为具有所需权限的IAM用户提供AWS访问密钥和机密密钥


无论选择哪种方案、第一步都是创建IAM策略。此策略仅包含从BlueXP在AWS中启动Connector实例所需的权限。

如果需要、您可以使用IAM来限制IAM策略 `Condition` Element。 https://["AWS文档：条件元素"^]


TIP: 在BlueXP创建Connector时、它会将一组新权限应用于Connector实例、以使Connector能够管理AWS资源。

.步骤
. 转到AWS IAM控制台。
. 单击*策略>创建策略*。
. 单击*。JSON*。
. 复制并粘贴以下策略：
+
请注意、此策略仅包含从BlueXP在AWS中启动Connector实例所需的权限。 link:reference-permissions-aws.html["连接器实例所需的查看权限"]。

+
[source, json]
----
{
    "Version": "2012-10-17",
    "Statement": [{
            "Effect": "Allow",
            "Action": [
                "iam:CreateRole",
                "iam:DeleteRole",
                "iam:PutRolePolicy",
                "iam:CreateInstanceProfile",
                "iam:DeleteRolePolicy",
                "iam:AddRoleToInstanceProfile",
                "iam:RemoveRoleFromInstanceProfile",
                "iam:DeleteInstanceProfile",
                "iam:PassRole",
                "ec2:DescribeInstanceStatus",
                "ec2:RunInstances",
                "ec2:ModifyInstanceAttribute",
                "ec2:CreateSecurityGroup",
                "ec2:DeleteSecurityGroup",
                "ec2:DescribeSecurityGroups",
                "ec2:RevokeSecurityGroupEgress",
                "ec2:AuthorizeSecurityGroupEgress",
                "ec2:AuthorizeSecurityGroupIngress",
                "ec2:RevokeSecurityGroupIngress",
                "ec2:CreateNetworkInterface",
                "ec2:DescribeNetworkInterfaces",
                "ec2:DeleteNetworkInterface",
                "ec2:ModifyNetworkInterfaceAttribute",
                "ec2:DescribeSubnets",
                "ec2:DescribeVpcs",
                "ec2:DescribeDhcpOptions",
                "ec2:DescribeKeyPairs",
                "ec2:DescribeRegions",
                "ec2:DescribeInstances",
                "ec2:CreateTags",
                "ec2:DescribeImages",
                "cloudformation:CreateStack",
                "cloudformation:DeleteStack",
                "cloudformation:DescribeStacks",
                "cloudformation:DescribeStackEvents",
                "cloudformation:ValidateTemplate",
                "ec2:AssociateIamInstanceProfile",
                "ec2:DescribeIamInstanceProfileAssociations",
                "ec2:DisassociateIamInstanceProfile",
                "iam:GetRole",
                "iam:TagRole",
                "iam:ListRoles",
                "kms:ListAliases"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "ec2:TerminateInstances"
            ],
            "Condition": {
                "StringLike": {
                    "ec2:ResourceTag/OCCMInstance": "*"
                }
            },
            "Resource": [
                "arn:aws:ec2:*:*:instance/*"
            ]
        }
    ]
}
----
. 单击*下一步*并根据需要添加标记。
. 单击*下一步*并输入名称和问题描述。
. 单击*创建策略*。
. 将策略附加到BlueXP可以承担的IAM角色或IAM用户、以便您可以为BlueXP提供访问密钥：
+
** (选项1)设置一个可由BlueXP承担的IAM角色：
+
... 转到目标帐户中的 AWS IAM 控制台。
... 在访问管理下，单击 * 角色 > 创建角色 * ，然后按照步骤创建角色。
... 在 * 可信实体类型 * 下，选择 * AWS 帐户 * 。
... 选择*其他AWS帐户*、然后输入BlueXP SaaS帐户的ID：952013314444
... 选择在上一节中创建的策略。
... 创建角色后、复制角色ARN、以便您可以在创建Connector时将其粘贴到BlueXP中。


** (选项2)为IAM用户设置权限、以便为BlueXP提供访问密钥：
+
... 在AWS IAM控制台中、单击*用户*、然后选择用户名。
... 单击*添加权限>直接附加现有策略*。
... 选择创建的策略。
... 单击*下一步*、然后单击*添加权限*。
... 确保您具有IAM用户的访问密钥和机密密钥。






.结果
现在、您应该拥有具有所需权限的IAM角色、或者拥有所需权限的IAM用户。从BlueXP创建Connector时、您可以提供有关角色或访问密钥的信息。



== 在从AWS Marketplace部署时设置Connector的权限

在AWS中创建IAM策略并将其附加到IAM角色。从AWS Marketplace创建Connector时、系统将提示您选择此IAM角色。

.步骤
. 从IAM控制台中、创建策略：
+
.. 单击*策略>创建策略*。
.. 选择*。JSON*、然后复制并粘贴的内容 link:reference-permissions-aws.html["Connector的IAM策略"]。
.. 完成其余步骤以创建策略。
+
根据您计划使用的BlueXP服务、您可能需要创建第二个策略。

+
对于标准区域、权限会分布在两个策略中。由于AWS中受管策略的字符大小上限、因此需要使用两个策略。



. 返回IAM控制台、创建IAM角色：
+
.. 单击*角色>创建角色*。
.. 选择* AWS服务> EC2*。
.. 通过附加上一步创建的策略来添加权限。
.. 完成其余步骤以创建角色。




.结果
现在、您有一个IAM角色、可以在从AWS Marketplace部署期间与EC2实例关联。



== 设置手动安装后要分配的权限

如果您在AWS的自有Linux主机上手动安装Connector软件、则可以通过以下方式提供权限：

* 选项1：创建IAM策略并将这些策略附加到可以与EC2实例关联的IAM角色。
* 选项2：为BlueXP提供具有所需权限的IAM用户的AWS访问密钥。


[role="tabbed-block"]
====
.IAM角色
--
.步骤
. 从IAM控制台中、创建策略：
+
.. 单击*策略>创建策略*。
.. 选择*。JSON*、然后复制并粘贴的内容 link:reference-permissions-aws.html["Connector的IAM策略"]。
.. 完成其余步骤以创建策略。
+
根据您计划使用的BlueXP服务、您可能需要创建第二个策略。

+
对于标准区域、权限会分布在两个策略中。由于AWS中受管策略的字符大小上限、因此需要使用两个策略。 link:reference-permissions-aws.html["详细了解Connector的IAM策略"]。



. 返回IAM控制台、创建IAM角色：
+
.. 单击*角色>创建角色*。
.. 选择* AWS服务> EC2*。
.. 通过附加上一步创建的策略来添加权限。
.. 完成其余步骤以创建角色。




.结果
现在、您可以在安装Connector后将IAM角色与EC2实例关联。 link:task-provide-permissions-aws.html["了解如何为BlueXP提供这些权限"]。

--
.AWS访问密钥
--
.步骤
. 从IAM控制台中、创建策略：
+
.. 单击*策略>创建策略*。
.. 选择*。JSON*、然后复制并粘贴的内容 link:reference-permissions-aws.html["Connector的IAM策略"]。
.. 完成其余步骤以创建策略。
+
根据您计划使用的BlueXP服务、您可能需要创建第二个策略。

+
对于标准区域、权限会分布在两个策略中。由于AWS中受管策略的字符大小上限、因此需要使用两个策略。 link:reference-permissions-aws.html["详细了解Connector的IAM策略"]。



. 将策略附加到IAM用户。
+
** https://["AWS 文档：创建 IAM 角色"^]
** https://["AWS 文档：添加和删除 IAM 策略"^]


. 确保用户具有可在安装Connector后添加到BlueXP的访问密钥。


.结果
您现在拥有一个IAM用户、该用户具有所需权限、并具有一个可提供给BlueXP的访问密钥。 link:task-provide-permissions-aws.html["了解如何为BlueXP提供这些权限"]。

--
====