---
sidebar: sidebar 
permalink: task-set-up-networking-aws.html 
keywords: aws networking, networking, connector networking, ports, proxy server, outbound internet, endpoints, urls, vpc, subnet 
summary: 设置您的网络、以便Connector可以管理混合云环境中的资源和流程。例如、您需要确保目标网络可以连接、并且可以访问出站Internet。 
---
= 设置AWS网络
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
设置您的网络、以便Connector可以管理混合云环境中的资源和流程。例如、您需要确保目标网络可以连接、并且可以访问出站Internet。



== VPC和子网

创建Connector时、需要指定此Connector应驻留的VPC和子网。



== 连接到目标网络

Connector需要与您计划创建和管理工作环境的位置建立网络连接。



== 出站 Internet 访问

部署 Connector 的网络位置必须具有出站 Internet 连接。从BlueXP控制台部署Connector时、还需要从Web浏览器进行出站Internet访问。



=== 从BlueXP控制台访问的端点

当您使用通过SaaS层提供的基于Web的BlueXP控制台时、它会与多个端点联系以完成数据管理任务。这包括从BlueXP控制台部署Connector所需访问的端点。

link:reference-networking-saas-console.html["从BlueXP控制台查看已联系的端点列表"]。



=== 在手动安装期间访问的端点

在您自己的Linux主机上手动安装Connector时、Connector安装程序需要在安装过程中访问以下URL：

* \https://support.netapp.com
* \https://mysupport.netapp.com
* \https://cloudmanager.cloud.netapp.com/tenancy
* \https://stream.cloudmanager.cloud.netapp.com
* \https://production-artifacts.cloudmanager.cloud.netapp.com
* \https://*.blob.core.windows.net
* \https://cloudmanagerinfraprod.azurecr.io


主机可能会在安装期间尝试更新操作系统软件包。主机可以联系这些操作系统软件包的不同镜像站点。



=== 从连接器连接的端点

Connector需要通过出站Internet访问与以下端点联系、以便管理公共云环境中的资源和流程、以实现日常运营。

[cols="2a,1a"]
|===
| 端点 | 目的 


 a| 
AWS 服务（ AmazonAWS.com ）：

* 云形成
* 弹性计算云（ EC2 ）
* 身份和访问管理(IAM)
* 密钥管理服务（ KMS ）
* 安全令牌服务（ STS ）
* 简单存储服务 (S3)

 a| 
管理AWS中的资源。确切的端点取决于部署 Connector 的区域。 https://docs.aws.amazon.com/general/latest/gr/rande.html["有关详细信息、请参见AWS文档"^]



 a| 
\https://support.netapp.com
 a| 
获取许可信息并向 NetApp 支持部门发送 AutoSupport 消息。



 a| 
\https://*.api.bluexp.netapp.com

\https://api.bluexp.netapp.com

\https://*.cloudmanager.cloud.netapp.com

\https://cloudmanager.cloud.netapp.com
 a| 
在BlueXP中提供SaaS功能和服务。

请注意、Connector目前正在联系cloudmanager.cloud.netapp.com"、但在即将发布的版本中、它将开始联系api.bluexp.netapp.com"。



 a| 
\https://*.blob.core.windows.net

\https://cloudmanagerinfraprod.azurecr.io
 a| 
升级 Connector 及其 Docker 组件。

|===


== 代理服务器

如果您的组织需要为所有传出Internet流量部署代理服务器、请获取有关HTTP或HTTPS代理的以下信息。您需要在安装期间提供此信息。

* IP 地址
* 凭据
* HTTPS证书




== 端口

除非您启动连接器或将连接器用作代理将AutoSupport消息从Cloud Volumes ONTAP发送到NetApp支持、否则不会有传入连接器的流量。

* 通过 HTTP （ 80 ）和 HTTPS （ 443 ），您可以访问本地 UI ，在极少数情况下，您可以使用此界面。
* 只有在需要连接到主机进行故障排除时，才需要使用 SSH （ 22 ）。
* 如果您在出站Internet连接不可用的子网中部署Cloud Volumes ONTAP 系统、则需要通过端口3128进行入站连接。
+
如果Cloud Volumes ONTAP系统没有用于发送AutoSupport消息的出站Internet连接、BlueXP会自动将这些系统配置为使用连接器附带的代理服务器。唯一的要求是确保Connector的安全组允许通过端口3128进行入站连接。部署Connector后、您需要打开此端口。





== IP地址限制

可能与172范围内的IP地址冲突。 https://docs.netapp.com/us-en/bluexp-setup-admin/reference-limitations.html["了解有关此限制的更多信息"]。
