---
sidebar: sidebar 
permalink: task-set-up-permissions-google.html 
keywords: set up permissions, set up gcp permissions, set up google cloud permissions, google permissions, gcp permissions, service account, create service account, gcp service account, google service account 
summary: 设置Google Cloud权限、以便您可以使用BlueXP在Google Cloud中管理数据和存储基础架构。 
---
= 设置Google Cloud权限
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在Google Cloud中设置权限、以便您可以使用管理数据和存储基础架构所需的权限部署Connector。

您需要按如下所示设置Google Cloud权限：

* 如果您计划从BlueXP或使用gcloud创建Connector、则需要为要部署Connector VM的Google Cloud用户设置权限。
* 通过创建角色并将此角色授予服务帐户来设置Connector的权限。
+
您将此服务帐户与Connector VM关联、以便BlueXP具有所需的权限。



根据您的配置、您可能还需要完成以下步骤：

* 在项目之间设置权限
* 设置共享VPC的权限




== 设置从BlueXP或gcloud创建Connector的权限

在从BlueXP或使用gcloud部署Connector之前、您需要确保Google Cloud帐户具有正确的权限。

.步骤
. 在Google Cloud中创建自定义角色：
+
.. 创建包含以下权限的YAML文件：
+
[source, yaml]
----
title: Connector deployment policy
description: Permissions for the user who deploys the Connector from BlueXP
stage: GA
includedPermissions:
- compute.disks.create
- compute.disks.get
- compute.disks.list
- compute.disks.setLabels
- compute.disks.use
- compute.firewalls.create
- compute.firewalls.delete
- compute.firewalls.get
- compute.firewalls.list
- compute.globalOperations.get
- compute.images.get
- compute.images.getFromFamily
- compute.images.list
- compute.images.useReadOnly
- compute.instances.attachDisk
- compute.instances.create
- compute.instances.get
- compute.instances.list
- compute.instances.setDeletionProtection
- compute.instances.setLabels
- compute.instances.setMachineType
- compute.instances.setMetadata
- compute.instances.setTags
- compute.instances.start
- compute.instances.updateDisplayDevice
- compute.machineTypes.get
- compute.networks.get
- compute.networks.list
- compute.networks.updatePolicy
- compute.projects.get
- compute.regions.get
- compute.regions.list
- compute.subnetworks.get
- compute.subnetworks.list
- compute.zoneOperations.get
- compute.zones.get
- compute.zones.list
- deploymentmanager.compositeTypes.get
- deploymentmanager.compositeTypes.list
- deploymentmanager.deployments.create
- deploymentmanager.deployments.delete
- deploymentmanager.deployments.get
- deploymentmanager.deployments.list
- deploymentmanager.manifests.get
- deploymentmanager.manifests.list
- deploymentmanager.operations.get
- deploymentmanager.operations.list
- deploymentmanager.resources.get
- deploymentmanager.resources.list
- deploymentmanager.typeProviders.get
- deploymentmanager.typeProviders.list
- deploymentmanager.types.get
- deploymentmanager.types.list
- resourcemanager.projects.get
- compute.instances.setServiceAccount
- iam.serviceAccounts.list
----
.. 从Google Cloud激活Cloud Shell。
.. 上传包含所需权限的YAML文件。
.. 使用创建自定义角色 `gcloud iam roles create` 命令：
+
以下示例将在项目级别创建一个名为"connectorDeployment"的角色：

+
gcloud iam角色用于创建connectorDeployment -project=MyProject -file=connector-deployment.yaml

+
https://cloud.google.com/iam/docs/creating-custom-roles#iam-custom-roles-create-gcloud["Google Cloud文档：创建和管理自定义角色"^]



. 将此自定义角色分配给要从BlueXP或使用gcloud部署Connector的用户。
+
https://cloud.google.com/iam/docs/granting-changing-revoking-access#grant-single-role["Google Cloud文档：授予单个角色"^]



.结果
Google Cloud用户现在具有创建Connector所需的权限。



== 设置Connector的权限

要为Connector提供BlueXP在Google Cloud中管理资源所需的权限、需要一个服务帐户。您需要将此服务帐户与Connector VM关联。

.步骤
. 在Google Cloud中创建自定义角色：
+
.. 创建包含内容的YAML文件 link:reference-permissions-gcp.html["Connector的服务帐户权限"]。
.. 从Google Cloud激活Cloud Shell。
.. 上传包含所需权限的YAML文件。
.. 使用创建自定义角色 `gcloud iam roles create` 命令：
+
以下示例将在项目级别创建一个名为"connector"的角色：

+
`gcloud iam roles create connector --project=myproject --file=connector.yaml`

+
https://cloud.google.com/iam/docs/creating-custom-roles#iam-custom-roles-create-gcloud["Google Cloud文档：创建和管理自定义角色"^]



. 在Google Cloud中创建服务帐户：
+
.. 从IAM和Admin服务中，选择*服务帐户>创建服务帐户*。
.. 输入服务帐户详细信息，然后选择*创建并继续*。
.. 选择刚刚创建的角色。
.. 完成其余步骤以创建角色。
+
https://cloud.google.com/iam/docs/creating-managing-service-accounts#creating_a_service_account["Google Cloud文档：创建服务帐户"^]





.结果
已设置Connector VM的服务帐户。



== 在项目之间设置权限

如果您计划将Cloud Volumes ONTAP 系统部署在与Connector所在项目不同的项目中、则需要为Connector的服务帐户提供对这些项目的访问权限。

例如、假设Connector位于项目1中、而您希望在项目2中创建Cloud Volumes ONTAP 系统。您需要授予对项目2中服务帐户的访问权限。

.步骤
. 在Google Cloud控制台中、转到IAM服务并选择要在其中创建Cloud Volumes ONTAP 系统的项目。
. 在* IAM *页面上、选择*授予访问权限*并提供所需的详细信息。
+
** 输入Connector服务帐户的电子邮件。
** 选择Connector的自定义角色。
** 选择 * 保存 * 。




有关详细信息，请参见 https://cloud.google.com/iam/docs/granting-changing-revoking-access#grant-single-role["Google Cloud文档"^]



== 设置共享VPC权限

如果您使用共享VPC将资源部署到服务项目中、则需要准备您的权限。

此表仅供参考，您的环境应在 IAM 配置完成后反映权限表。

[cols="10,10,10,20,20,30"]
|===
| 身份 | 创建者 | 托管在中 | 服务项目权限 | 托管项目权限 | 目的 


| 用于部署Connector的Google帐户 | 自定义 | 服务项目  a| 
link:task-set-up-permissions-google.html#set-up-permissions-to-create-the-connector-from-bluexp-or-gcloud["连接器部署策略"]
 a| 
compute.networkUser
| 在服务项目中部署Connector 


| 连接器服务帐户 | 自定义 | 服务项目  a| 
link:reference-permissions-gcp.html["连接器服务帐户策略"]
 a| 
* compute.networkUser
* deploymentmanager.editor

| 在服务项目中部署和维护 Cloud Volumes ONTAP 和服务 


| Cloud Volumes ONTAP 服务帐户 | 自定义 | 服务项目  a| 
* storage.admin
* 成员：BlueXP服务帐户serviceAccount.user

| 不适用 | (可选)用于数据分层和BlueXP备份和恢复 


| Google API 服务代理 | Google Cloud | 服务项目  a| 
（默认）编辑器
 a| 
compute.networkUser
| 代表部署与Google Cloud API进行交互。允许BlueXP使用共享网络。 


| Google Compute Engine 默认服务帐户 | Google Cloud | 服务项目  a| 
（默认）编辑器
 a| 
compute.networkUser
| 代表部署部署部署部署Google Cloud实例和计算基础架构。允许BlueXP使用共享网络。 
|===
注释：

. 只有在未向部署传递防火墙规则并选择让BlueXP为您创建这些规则的情况下、主机项目才需要使用deploymentmanager.editor.如果未指定任何规则、BlueXP将在包含VPC0防火墙规则的主机项目中创建部署。
. 只有当您不向部署传递防火墙规则并选择让BlueXP为您创建这些规则时、才需要firewall.create和firewall.delete。这些权限位于BlueXP帐户.YAML文件中。如果要使用共享 VPC 部署 HA 对，则会使用这些权限为 VC1 ， 2 和 3 创建防火墙规则。对于所有其他部署，这些权限还将用于为 VPC0 创建规则。
. 对于数据分层，分层服务帐户必须在服务帐户上具有 serviceAccount.user 角色，而不仅仅是在项目级别。目前，如果您在项目级别分配 serviceAccount.user ，则在使用 getIAMPolicy 查询服务帐户时不会显示权限。

