---
sidebar: sidebar 
permalink: task-logging-in.html 
keywords: logging in, log in, sign in, signing in, cloud central, netapp cloud central, user account, federated, federation, federated login, federation login, login with netapp, log in with netapp, sign up, create account 
summary: 登录BlueXP的方式取决于您的帐户使用的BlueXP部署模式。 
---
= 登录到BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
登录BlueXP的方式取决于您的帐户使用的BlueXP部署模式。

Connector包括一个本地UI、可从Connector主机访问此UI。此UI面向在受限模式或专用模式下使用BlueXP的客户。在标准模式下使用BlueXP时、您应从访问用户界面 https://console.bluexp.netapp.com/["BlueXP SaaS控制台"^]

link:concept-modes.html["了解BlueXP部署模式"]。

[role="tabbed-block"]
====
.标准模式
--
注册BlueXP后、您可以从基于Web的控制台登录、开始管理数据和存储基础架构。

.关于此任务
您可以使用以下选项之一登录到基于BlueXP Web的控制台：

* 您的现有NetApp 支持站点 (NSS)凭据
* 使用您的电子邮件地址和密码登录NetApp云
* 联合连接
+
您可以使用单点登录使用公司目录中的凭据（联合身份）登录。 link:concept-federation.html["了解如何在BlueXP中使用身份联合"]。



.步骤
. 打开Web浏览器并转到 https://console.bluexp.netapp.com["BlueXP控制台"^]
. 在*登录*页面上、输入与您的登录关联的电子邮件地址。
. 根据与您的登录关联的身份验证方法、系统将提示您输入凭据：
+
** NetApp云凭据：输入密码
** 联合用户：输入您的联合身份凭据
** NetApp 支持站点 帐户：输入您的NetApp 支持站点 凭据




.结果
您现在已登录、可以开始使用BlueXP管理混合多云基础架构。

--
.受限模式
--
在受限模式下使用BlueXP时、您需要从连接器本地运行的用户界面登录到BlueXP控制台。

.关于此任务
当您的帐户设置为受限模式时、BlueXP支持使用以下选项之一登录：

* 使用您的电子邮件地址和密码登录NetApp云
* 联合连接
+
您可以使用单点登录使用公司目录中的凭据（联合身份）登录。 link:concept-federation.html["了解如何在BlueXP中使用身份联合"]。



.步骤
. 打开 Web 浏览器并输入以下 URL ：
+
https://_ipaddress_[]

+
_ipaddress_可以是localhost、专用IP地址或公共IP地址、具体取决于安装Connector的主机的配置。例如、您可能需要输入与Connector主机连接的主机的专用IP地址。

. 输入您的用户名和密码以登录。


.结果
您现在已登录、可以开始使用BlueXP管理混合多云基础架构。

--
.私有模式
--
在专用模式下使用BlueXP时、您需要从连接器本地运行的用户界面登录到BlueXP控制台。

.关于此任务
专用模式支持本地用户管理和访问。不通过BlueXP的云服务提供身份验证。

.步骤
. 打开 Web 浏览器并输入以下 URL ：
+
https://_ipaddress_[]

+
_ipaddress_可以是localhost、专用IP地址或公共IP地址、具体取决于安装Connector的主机的配置。例如、您可能需要输入与Connector主机连接的主机的专用IP地址。

. 输入您的用户名和密码以登录。


.结果
您现在已登录、可以开始使用BlueXP管理混合多云基础架构。

--
====