= 连接器3.9.52
:allow-uri-read: 




=== 连接器3.9.52

此版本的BlueXP  连接器提供了一些小的安全改进和错误修复、以及一些附加更新。

目前、3.9.52版本可用于标准模式和受限模式。



==== 支持Docker 27和Docker 28

连接器现在支持Docker 27和Docker 28。



==== Cloud Volumes ONTAP

当连接器不合规或停机超过 14 天时，Cloud Volumes ONTAP 节点将不再关闭。当 Cloud Volumes ONTAP 失去对连接器的访问权限时，它仍会发送事件管理消息。此更改是为了确保即使连接器长时间停机，Cloud Volumes ONTAP 也能继续运行。此更改不会改变连接器的合规性要求。



=== Keystone管理可在BlueXP  中使用

BlueXP  中的NetApp Keystone测试版增加了对Keystone管理的访问权限。您可以从BlueXP  的左侧导航栏访问NetApp Keystone测试版的注册页面。



=== BlueXP  身份和访问管理(IAM)



==== 新的存储管理角色

存储管理员、系统健康专家和存储查看器角色可用，可以分配给用户。

这些角色使您能够管理组织中的谁可以发现和管理存储资源，以及查看存储健康信息和执行软件更新。

这些角色支持控制对以下存储资源的访问：

* E系列系统
* StorageGRID 系统
* 内部部署 ONTAP 系统


您还可以使用这些角色来控制对以下 BlueXP 服务的访问：

* 软件更新
* 数字顾问
* 运营故障恢复能力
* 经济效率
* 可持续性


已添加以下角色：

* *存储管理员*
+
管理组织中存储资源的存储运行状况、治理和发现。此角色还可以对存储资源执行软件更新。

* *系统健康专家*
+
管理组织中存储资源的存储运行状况和治理。此角色还可以对存储资源执行软件更新。此角色无法修改或删除工作环境。

* *存储查看器*
+
查看存储健康信息和治理数据。

+
link:https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["了解访问角色。"^]


