= 
:allow-uri-read: 


.开始之前
您应具备以下条件：

* 安装Connector的root权限。
* 有关代理服务器的详细信息、如果从Connector访问Internet需要代理。
+
您可以选择在安装后配置代理服务器、但这样做需要重新启动Connector。

* CA签名证书、如果代理服务器使用HTTPS或代理是截获代理。



NOTE: 手动安装连接器时，无法为透明代理服务器设置证书。如果需要为透明代理服务器设置证书，则必须在安装后使用维护控制台。了解有关的更多信息link:reference-connector-maint-console.html["连接器维护控制台"]。

.关于此任务
NetApp 支持站点上提供的安装程序可能是早期版本。安装后，如果有新版本可用， Connector 会自动进行更新。

.步骤
. 如果在主机上设置了_http_proxy_或_https_proxy_系统变量、请将其删除：
+
[source, cli]
----
unset http_proxy
unset https_proxy
----
+
如果不删除这些系统变量、安装将失败。

. 从下载Connector软件 https://mysupport.netapp.com/site/products/all/details/cloud-manager/downloads-tab["NetApp 支持站点"^]，然后将其复制到 Linux 主机。
+
您应下载用于您的网络或云中的"联机"Connector安装程序。Connector可以使用单独的"脱机"安装程序、但只有专用模式部署才支持此安装程序。

. 分配运行脚本的权限。
+
[source, cli]
----
chmod +x BlueXP-Connector-Cloud-<version>
----
+
其中、<version> 是您下载的连接器版本。

. 运行安装脚本。
+
[source, cli]
----
 ./BlueXP-Connector-Cloud-<version> --proxy <HTTP or HTTPS proxy server> --cacert <path and file name of a CA-signed certificate>
----
+
如果您的网络需要代理才能访问互联网，则需要添加代理信息。您可以添加透明代理或显式代理。--proxy 和 --cacert 参数是可选的，系统不会提示您添加它们。如果您有代理服务器、则需要输入所示的参数。

+
以下是使用 CA 签名证书配置显式代理服务器的示例：

+
[source, cli]
----
 ./BlueXP-Connector-Cloud-v3.9.40--proxy https://user:password@10.0.0.30:8080/ --cacert /tmp/cacert/certificate.cer
----
+
-proxy会将Connector配置为使用以下格式之一的HTTP或HTTPS代理服务器：

+
** \http://address:port
** \http://user-name:password@address:port
** \http://domain-name%92user-name:password@address:port
** \https://address:port
** \https://user-name:password@address:port
** \https://domain-name%92user-name:password@address:port
+
请注意以下事项：

+
*** 用户可以是本地用户或域用户。
*** 对于域用户、必须对\使用ASCII代码、如上所示。
*** BlueXP不支持包含@字符的用户名或密码。
*** 如果密码包含以下任一特殊字符，则必须在该特殊字符前面加上反斜杠：&或!
+
例如：

+
\http://bxpproxyuser:netapp1\!@address:3128

+
-cacert指定用于在Connector和代理服务器之间进行HTTPS访问的CA签名证书。HTTPS代理服务器、拦截代理服务器、透明代理服务器都需要此参数。



+
以下是配置透明代理服务器的示例。配置透明代理时，无需定义代理服务器。只需向连接器主机添加 CA 签名的证书即可：



+
[source, cli]
----
 ./BlueXP-Connector-Cloud-v3.9.40 --cacert /tmp/cacert/certificate.cer
----
. 如果您使用 Podman，则需要调整 aardvark-dns 端口。
+
.. 通过 SSH 连接到 BlueXP Connector 虚拟机。
.. 打开 podman_/usr/share/containers/containers.conf_ 文件并修改 Aardvark DNS 服务的所选端口。例如，将其更改为 54。
+
[source, cli]
----
vi /usr/share/containers/containers.conf
...
# Port to use for dns forwarding daemon with netavark in rootful bridge
# mode and dns enabled.
# Using an alternate port might be useful if other DNS services should
# run on the machine.
#
dns_bind_port = 54
...
Esc:wq
----
.. 重新启动 Connector 虚拟机。




. 等待安装完成。
+
在安装结束时、如果您指定了代理服务器、则Connector服务(occa)将重新启动两次。

. 从已连接到 Connector 虚拟机的主机打开 Web 浏览器，然后输入以下 URL ：
+
https://_ipaddress_[]

. 登录后，设置 Connector ：
+
.. 指定要与连接器关联的BlueXP  组织。
.. 输入系统名称。
.. 在*是否在安全环境中运行？*下、保持禁用受限模式。
+
您应始终禁用受限模式、因为这些步骤说明了如何在标准模式下使用BlueXP。只有在您拥有安全环境并希望将此帐户与BlueXP后端服务断开连接时、才应启用受限模式。如果是这种情况、 link:task-quick-start-restricted-mode.html["按照步骤在受限模式下开始使用BlueXP"]。

.. 选择*开始*。



